In [7]:
import mobile_env 
import gymnasium as gym
from stable_baselines3 import PPO
from stable_baselines3.common.env_util import make_vec_env
env = gym.make('mobile-small-central-v0')
import torch

In [11]:
tensor = torch.tensor([[1, 0, 0, 0],
        [0, 0, 1, 0],
        [0.2365, 0.2600, 0.2292, 0.2743],
        [0.2570, 0.2760, 0.2122, 0.2549],
        [0.2342, 0.2347, 0.2492, 0.2819]])

torch.distributions.Categorical(tensor).sample()

tensor([0, 2, 0, 0, 1])

In [5]:
nn(env.observation_space.sample())

5:4
tensor([[0.2740, 0.2147, 0.2405, 0.2708],
        [0.2456, 0.2367, 0.2210, 0.2967],
        [0.2365, 0.2600, 0.2292, 0.2743],
        [0.2570, 0.2760, 0.2122, 0.2549],
        [0.2342, 0.2347, 0.2492, 0.2819]], grad_fn=<SoftmaxBackward0>)


RuntimeError: a Tensor with 5 elements cannot be converted to Scalar

In [3]:
from reinforce import PiApproximationWithNN
from reinforce import Rei

actions_shape = (env.NUM_STATIONS+1, env.NUM_USERS)
nn =PiApproximationWithNN(env.observation_space.sample().shape, actions_shape, 0.1)
nn(env.observation_space.sample())


5:4
tensor([[0.2712, 0.2308, 0.2357, 0.2624],
        [0.2458, 0.2474, 0.2229, 0.2838],
        [0.2326, 0.2643, 0.2294, 0.2737],
        [0.2566, 0.2686, 0.2285, 0.2463],
        [0.2377, 0.2257, 0.2595, 0.2772]], grad_fn=<SoftmaxBackward0>)


/Users/carlosmarinoguera/miniconda3/envs/rl_mobile_env/lib/python3.9/site-packages/gymnasium/core.py:311: UserWarning: WARN: env.NUM_STATIONS to get variables from other wrappers is deprecated and will be removed in v1.0, to get this variable you can do `env.unwrapped.NUM_STATIONS` for environment variables or `env.get_wrapper_attr('NUM_STATIONS')` that will search the reminding wrappers.
  logger.warn(
/Users/carlosmarinoguera/miniconda3/envs/rl_mobile_env/lib/python3.9/site-packages/gymnasium/core.py:311: UserWarning: WARN: env.NUM_USERS to get variables from other wrappers is deprecated and will be removed in v1.0, to get this variable you can do `env.unwrapped.NUM_USERS` for environment variables or `env.get_wrapper_attr('NUM_USERS')` that will search the reminding wrappers.
  logger.warn(


RuntimeError: a Tensor with 5 elements cannot be converted to Scalar

In [6]:
vec_env = make_vec_env('mobile-small-central-v0')

model = PPO("MlpPolicy", vec_env, verbose=1, device='mps')
model.learn(total_timesteps=1000000)

Using mps device
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 100      |
|    ep_rew_mean     | -43.1    |
| time/              |          |
|    fps             | 67       |
|    iterations      | 1        |
|    time_elapsed    | 30       |
|    total_timesteps | 2048     |
---------------------------------


KeyboardInterrupt: 

In [4]:


done = False
obs = vec_env.reset()
while not done:
    action, _states = model.predict(obs)
    obs, rewards, dones, info = vec_env.step(action)
    vec_env.render("human")


NameError: name 'vec_env' is not defined

In [20]:
env.action_space.sample()

array([1, 1, 0, 0, 0])

In [2]:
print(len(env.action_space))
print(env.action_space[0].n)

5
4


/Users/carlosmarinoguera/miniconda3/envs/rl_mobile_env/lib/python3.9/site-packages/gymnasium/core.py:311: UserWarning: WARN: env.NUM_STATIONS to get variables from other wrappers is deprecated and will be removed in v1.0, to get this variable you can do `env.unwrapped.NUM_STATIONS` for environment variables or `env.get_wrapper_attr('NUM_STATIONS')` that will search the reminding wrappers.
  logger.warn(
/Users/carlosmarinoguera/miniconda3/envs/rl_mobile_env/lib/python3.9/site-packages/gymnasium/core.py:311: UserWarning: WARN: env.NUM_USERS to get variables from other wrappers is deprecated and will be removed in v1.0, to get this variable you can do `env.unwrapped.NUM_USERS` for environment variables or `env.get_wrapper_attr('NUM_USERS')` that will search the reminding wrappers.
  logger.warn(


3:5


RuntimeError: shape '[3, 5]' is invalid for input of size 3