In [11]:
env.NUM_USERS

15

In [4]:
import torch

x = torch.ones((2,2))
print(x)
print(-x)

tensor([[1., 1.],
        [1., 1.]])
tensor([[-1., -1.],
        [-1., -1.]])


In [7]:
gym.pprint_registry()

===== classic_control =====
Acrobot-v1             CartPole-v0            CartPole-v1
MountainCar-v0         MountainCarContinuous-v0 Pendulum-v1
===== phys2d =====
phys2d/CartPole-v0     phys2d/CartPole-v1     phys2d/Pendulum-v0
===== box2d =====
BipedalWalker-v3       BipedalWalkerHardcore-v3 CarRacing-v2
LunarLander-v2         LunarLanderContinuous-v2
===== toy_text =====
Blackjack-v1           CliffWalking-v0        FrozenLake-v1
FrozenLake8x8-v1       Taxi-v3
===== tabular =====
tabular/Blackjack-v0   tabular/CliffWalking-v0
===== mujoco =====
Ant-v2                 Ant-v3                 Ant-v4
HalfCheetah-v2         HalfCheetah-v3         HalfCheetah-v4
Hopper-v2              Hopper-v3              Hopper-v4
Humanoid-v2            Humanoid-v3            Humanoid-v4
HumanoidStandup-v2     HumanoidStandup-v4     InvertedDoublePendulum-v2
InvertedDoublePendulum-v4 InvertedPendulum-v2    InvertedPendulum-v4
Pusher-v2              Pusher-v4              Reacher-v2
Reacher-v4         

In [21]:
r1 = np.random.random((2,5))
print(r1)

print(r1[:,4:].sum(axis=1))

[[0.6775444  0.28579552 0.65127206 0.4821777  0.21202398]
 [0.08640334 0.22247023 0.56739622 0.01566263 0.13718705]]
[0.21202398 0.13718705]


: 

In [2]:
# (0,1,2,2,1)
# ((0,0))
from collections import OrderedDict
actions = [0,1,2,2,1]
tupled = OrderedDict([(i, actions[i]) for i in range(len(actions))])


In [3]:
obs = env.observation_space.sample()

parsered_obs = np.array([array for array in obs.values()])
parsered_obs.shape

(5, 13)

In [4]:
import mobile_env 
import gymnasium as gym
from stable_baselines3 import PPO
from stable_baselines3.common.env_util import make_vec_env
import numpy as np

env = gym.make('mobile-small-ma-v0', render_mode='human')
env.reset()
observations, r, _, _, _ = env.step(tupled)


print(observations)
'''batched_obs = np.array([observations[key] for key in observations.keys()])
r = np.array([array for array in r.values()])
print(r)'''

{0: array([ 0.        ,  0.        ,  0.        ,  1.        ,  0.2516919 ,
        0.56135505, -1.        , -1.        , -1.        , -1.        ,
        0.        ,  0.        ,  0.        ], dtype=float32), 1: array([ 0.        ,  0.        ,  0.        ,  0.11989262,  0.1122832 ,
        1.        , -1.        , -1.        , -1.        , -1.        ,
        0.        ,  0.        ,  0.        ], dtype=float32), 2: array([ 0.        ,  1.        ,  0.        ,  0.4710008 ,  0.44577658,
        1.        , -0.14339764, -0.2793635 , -0.14339764, -1.        ,
        0.5       ,  0.5       ,  0.        ], dtype=float32), 3: array([ 0.        ,  0.        ,  0.        ,  0.03805785,  0.04028227,
        1.        , -1.        , -1.        , -1.        , -1.        ,
        0.        ,  0.        ,  0.        ], dtype=float32), 4: array([ 1.        ,  0.        ,  0.        ,  1.        ,  0.17299446,
        0.3024028 , -0.2793635 , -0.2793635 , -1.        , -1.        ,
        1.  

/Users/carlosmarinoguera/miniconda3/envs/rl_mobile_env/lib/python3.9/site-packages/gymnasium/utils/passive_env_checker.py:275: UserWarning: WARN: The reward returned by `step()` must be a float, int, np.integer or np.floating, actual type: <class 'dict'>
  logger.warn(


'batched_obs = np.array([observations[key] for key in observations.keys()])\nr = np.array([array for array in r.values()])\nprint(r)'

In [26]:
actions = []
for agent_id, obs in observations.items():
    action = np.argmax(obs[3:6])
    print(obs[3:6])
    # If we are connected to the best bs we do nothing
    if obs[action]:
        actions.append(0)

    # If connected to bs we disconnect
    elif sum(obs[0:3]) > 0:
            print('Disconnecting')
            conn_bs = obs[0:3].index(1)
            actions.append(conn_bs+1)
            print(conn_bs + 1)
    # If we are not connected we connect to the best bs
    else:
        actions.append(action + 1)
        print(action+1)
    


1
[1.         0.2516919  0.56135505]
3
[0.11989262 0.1122832  1.        ]
3
[0.4710008  0.44577658 1.        ]
3
[0.03805785 0.04028227 1.        ]
1
[1.         0.17299446 0.3024028 ]


In [28]:
import torch 
import torch.nn.functional as F
a = torch.tensor([0,1,0,2,3])
probabilities = F.softmax(torch.rand(5,4))
values = torch.rand(1,5)

one_hot = F.one_hot(a)

probs= one_hot * probabilities
print(probs)
sums = torch.sum(probs, dim=1)
print(values)
sums * values


tensor([[0.2976, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.2284, 0.0000, 0.0000],
        [0.1640, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.2608, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.2424]])
tensor([[0.0124, 0.9512, 0.8537, 0.9174, 0.3247]])


/var/folders/q0/lzrls2551w3btk7nl0c8dknw0000gn/T/ipykernel_56681/1022769036.py:4: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  probabilities = F.softmax(torch.rand(5,4))


tensor([[0.0037, 0.2173, 0.1400, 0.2392, 0.0787]])

In [19]:
env.action_space

Dict(0: Discrete(4), 1: Discrete(4), 2: Discrete(4), 3: Discrete(4), 4: Discrete(4))

In [20]:
env.render()

/Users/carlosmarinoguera/miniconda3/envs/rl_mobile_env/lib/python3.9/site-packages/gymnasium/utils/passive_env_checker.py:335: UserWarning: WARN: No render fps was declared in the environment (env.metadata['render_fps'] is None or not defined), rendering may occur at inconsistent fps.
  logger.warn(
2024-04-24 10:44:56.083 python[54934:1452302] Inconsistent set of values to create NSBitmapImageRep


In [11]:
tensor = torch.tensor([[1, 0, 0, 0],
        [0, 0, 1, 0],
        [0.2365, 0.2600, 0.2292, 0.2743],
        [0.2570, 0.2760, 0.2122, 0.2549],
        [0.2342, 0.2347, 0.2492, 0.2819]])

torch.distributions.Categorical(tensor).sample()

tensor([0, 2, 0, 0, 1])

In [3]:
env.action_space

MultiDiscrete([4 4 4 4 4])

In [9]:
env.observation_space.sample()

OrderedDict([(0,
              array([ 0.8955473 , -0.10306899, -0.8207377 ,  0.71955466,  0.08019269,
                      0.13806495, -0.9261017 ,  0.15187824,  0.7817163 , -0.16798289,
                      0.6710511 ,  0.33811823,  0.52643144], dtype=float32)),
             (1,
              array([-0.20929642,  0.47161365,  0.8119165 , -0.2029094 ,  0.881791  ,
                      0.552677  ,  0.7276691 ,  0.7032808 , -0.15544918, -0.40884727,
                      0.02058269, -0.08884903, -0.8195469 ], dtype=float32)),
             (2,
              array([-0.27622098,  0.06261311,  0.8199006 ,  0.47824782,  0.48189917,
                      0.05567513, -0.1164932 , -0.20234503, -0.06206719, -0.3990322 ,
                     -0.9562528 ,  0.06643494, -0.49132898], dtype=float32)),
             (3,
              array([ 0.18196487,  0.1535525 , -0.5078211 , -0.713702  ,  0.96007085,
                     -0.40530118, -0.18813589,  0.81908906,  0.5129964 ,  0.47318566,
          

In [43]:
from reinforce import PiApproximationWithNN
from reinforce import Rei

actions_shape = (env.NUM_STATIONS+1, env.NUM_USERS)
nn =PiApproximationWithNN(env.observation_space.sample().shape, actions_shape, 0.1)
nn(env.observation_space)


ImportError: cannot import name 'Rei' from 'reinforce' (/Users/carlosmarinoguera/Documents/class/UT/RL/PROJECT/reinforce.py)

In [14]:
print(obs)

[-0.79367965 -0.64000136 -0.17819194  0.56419516  0.42303452  0.9679094
 -0.53956735 -0.18181287 -0.32860035  0.23140877 -0.38320273  0.00650112
 -0.44249934  0.60337657  0.6381117   0.7247584  -0.7433741   0.984023
  0.9157227  -0.4720127   0.758845   -0.5291964  -0.2974816  -0.7711328
 -0.75767756 -0.34733924  0.4271143   0.29427668 -0.05141254  0.9171868
 -0.79921454 -0.15337321  0.9400537  -0.9858751   0.9446637 ]


In [17]:
obs = env.observation_space.sample()
env.reset()
import numpy as np
obs, _, _,_,_ = env.step(env.action_space.sample())
obs_per_user = 2 * env.NUM_STATIONS + 1

actions = []
for ue in range(env.NUM_USERS):
        offset = ue * obs_per_user
        snrs = np.array(obs[offset+env.NUM_STATIONS:offset+2*env.NUM_STATIONS])
        action = np.argmax(snrs)
        actions.append(action)
        print(f'SNRS : {snrs} \n action: {action}')

        

SNRS : [1.         0.02810937 0.01506933] 
 action: 0
SNRS : [0.03044292 1.         0.0137014 ] 
 action: 1
SNRS : [0.06937985 1.         0.9660871 ] 
 action: 1
SNRS : [1.         0.46188155 0.09939642] 
 action: 0
SNRS : [0.6148933  0.24630731 1.        ] 
 action: 2


In [4]:
vec_env = make_vec_env('mobile-small-central-v0')

model = PPO("MlpPolicy", vec_env, verbose=1, device='mps')
#model.learn(total_timesteps=1000000)

Using mps device


In [5]:
import torch
from stable_baselines3 import PPO
model = PPO.load('ppo.pth')

In [6]:

done = False
obs = vec_env.reset()
reward = 0
while not done:
    action, _states = model.predict(obs)
    obs, rewards, done, info = vec_env.step(action)
    vec_env.render("human")
    reward += rewards
    



/Users/carlosmarinoguera/miniconda3/envs/rl_mobile_env/lib/python3.9/site-packages/gymnasium/utils/passive_env_checker.py:335: UserWarning: WARN: No render fps was declared in the environment (env.metadata['render_fps'] is None or not defined), rendering may occur at inconsistent fps.
  logger.warn(


In [7]:
print(reward)

[-33.874615]


In [2]:
print(len(env.action_space))
print(env.action_space[0].n)

5
4


/Users/carlosmarinoguera/miniconda3/envs/rl_mobile_env/lib/python3.9/site-packages/gymnasium/core.py:311: UserWarning: WARN: env.NUM_STATIONS to get variables from other wrappers is deprecated and will be removed in v1.0, to get this variable you can do `env.unwrapped.NUM_STATIONS` for environment variables or `env.get_wrapper_attr('NUM_STATIONS')` that will search the reminding wrappers.
  logger.warn(
/Users/carlosmarinoguera/miniconda3/envs/rl_mobile_env/lib/python3.9/site-packages/gymnasium/core.py:311: UserWarning: WARN: env.NUM_USERS to get variables from other wrappers is deprecated and will be removed in v1.0, to get this variable you can do `env.unwrapped.NUM_USERS` for environment variables or `env.get_wrapper_attr('NUM_USERS')` that will search the reminding wrappers.
  logger.warn(


3:5


RuntimeError: shape '[3, 5]' is invalid for input of size 3